server:
  port: 8001

spring:  application:    name: admin client
  # 配置 Admin Server 的地址  boot:    admin:      client:        url: http://localhost:8000

# 打开客户端 Actuator 的监控
management:  endpoints:    jmx:      exposure:        include: "*"