# turbine：hystrix dashboard只能监控一个服务，turbine可以将多个服务的信息聚合提供给dashboard显示
# 添加turbine、Eureka Discovery Client启动依赖
spring:
  application:
    name: turbin

server:
  port: 5001

eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer1:8001/eureka, http://eurekaServer2:8002/eureka

turbine:
  # 要监控的服务名
  app-config: ServiceName微服务名, feign
  cluster-name-expression: new String("default")
# 启动类添加@EnableTurbine和@EnableDiscoveryClient注解
# 访问http://localhost:5001/turbine.stream获得监控端点href，将href填入hystrix dashboard中
