#端口号
server:
  port: 7979
#数据库的配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: waconde
    password: waconde

mybatis-plus:
  # xml地址
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: site.waconde.pageLearn.dto
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true